name: Docker Image CI

on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - mongodb
    paths:
      - '**'
  pull_request:
    branches:
      - mongodb
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_REPOSITORY: 958877748/GoNorth

    steps:
    - uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ghcr.io/958877748/gonorth:latest
          ghcr.io/958877748/gonorth:${{ github.sha }}
          ghcr.io/958877748/gonorth:${{ github.ref_name }}
        labels: |
          org.opencontainers.image.source=${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.version=${{ github.ref_name }}
